# Default (dev) values
global:
  appName: housing-ecosystem
  imagePullSecrets:
    - name: ghcr-secret

api:
  image: ghcr.io/rparchman/housing-api:3bbe324d9d03d4e6c151add2542153c37184bba2
  replicas: 1
  imagePullSecrets:
    - name: ghcr-secret
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

scheduler:
  image: ghcr.io/rparchman/gis-scheduler:3bbe324d9d03d4e6c151add2542153c37184bba2
  replicas: 1
  imagePullSecrets:
    - name: ghcr-secret
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

ingress:
  enabled: true
  host: dev.housing.yourdomain.com

config:
  LOG_LEVEL: "info"

secrets:
  SLACK_WEBHOOK: ""
  EMAIL_SENDER: ""
  EMAIL_PASSWORD: ""
  EMAIL_RECIPIENT: ""
