apiVersion: v1
kind: Service
metadata:
  name: {{ include "housing-ecosystem.apiServiceName" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "housing-ecosystem.apiName" . }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
