apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "housing-ecosystem.apiName" . }}-config
data:
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "housing-ecosystem.schedulerName" . }}-config
data:
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
