apiVersion: v1
kind: Secret
metadata:
  name: {{ include "housing-ecosystem.apiName" . }}-secrets
type: Opaque
stringData:
  SLACK_WEBHOOK: {{ .Values.secrets.SLACK_WEBHOOK | quote }}
  EMAIL_SENDER: {{ .Values.secrets.EMAIL_SENDER | quote }}
  EMAIL_PASSWORD: {{ .Values.secrets.EMAIL_PASSWORD | quote }}
  EMAIL_RECIPIENT: {{ .Values.secrets.EMAIL_RECIPIENT | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "housing-ecosystem.schedulerName" . }}-secrets
type: Opaque
stringData:
  SLACK_WEBHOOK: {{ .Values.secrets.SLACK_WEBHOOK | quote }}
  EMAIL_SENDER: {{ .Values.secrets.EMAIL_SENDER | quote }}
  EMAIL_PASSWORD: {{ .Values.secrets.EMAIL_PASSWORD | quote }}
  EMAIL_RECIPIENT: {{ .Values.secrets.EMAIL_RECIPIENT | quote }}
